### ISSUE TITLE
MVC

### ISSUE THREAD

**Issue by alex85k** [HungryDoodles/LabOneForms#2]
Кажется, в показанной версии было 2 игры, а теперь одна. 
Нужны интерфейсы для слабой связи классов , отделение модели от отрисовки и управления.
(например, одна из моделей игры - тыкнуть по 5 объектам по очереди, а как они выглядят - дело Viewшек)

**Comment by HungryDoodles** [comment]
Сделал пуш, реализовано что-то подобное в системе частиц, которая никак не связана с формой, но отладочная информация о ней выводится через gridView
