### ISSUE TITLE
Пропущен TaoForm.cs

### ISSUE THREAD

**Issue by alex85k** [HungryDoodles/LabOneForms#5]
Чтобы иметь возможность это потестировать живьём, нужен TaoForm.cs
Забыли выложить или это часть Tao (не похоже)?

Кстати, TaoFramework теперь переименован в OpenTK и доступен через Nuget package manager (меню Project). OpenTK.GLControl.
Если есть время, можно обновиться - пакетные менеджеры полезны для профессионального развития... Классы перенесли, правда.

**Comment by HungryDoodles** [comment]
Запушил.
Почему-то гит не посчитал необходимым следить за этим файлом.
Также залил сами библиотеки Tao.
Если и обновлять библиотеку, то придётся переделывать класс/форму, по крайней мере переименовывать половину кода в TaoForm.cs... Это долго
